repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Updated Ruff version
  rev: v0.14.10
  hooks:
    # Run the linter
    - id: ruff-check
      types_or: [ python ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
    - id: mypy
      additional_dependencies: [types-Pillow, types-PyYAML]
      args: [--strict]